parameters:
#    nils_wisiol_credit_card.example.class: NilsWisiol\CreditCardBundle\Example

services:
#    nils_wisiol_credit_card.example:
#        class: %nils_wisiol_credit_card.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
